travis:
  secure:
    BINSTAR_TOKEN: asonfWPnvk8p+2GH46aJWfKc7LoZL2DkjIz3tUWTJLTQRaQVCZFNnTMGlgf2p341vRYIt8lrAc5ZajvkZzq7I6ge6AiAp27QPHhD+eYsqHifZcL8yVh3YGk3OrPuQoH0Bqc5g+7w6vlqajLjC3jhfehaCDQiGjNe+He2c0aIL0BLIXzC0euOn0y7s2HbHzsXhne1W27uDSRqouvyKze41zi8Jua2tqwmZkwX+C5WacrnIZ2etcHEVop5Bub7DrVXxcuYlNFJ8JdMhQON1dkdhngT8NL2+NOCFf4wgIGSsoCGxKXn7wMJvbKqKk5L8g8AXamBwA7OfZqkc0u2vv+Pt9+q7PBvY939TPJQXI13nyyrhQVqJRqjUP2RbmFUX6X5C0fz3DdkaUl3gNxZdlRluefrT0tj8IoFVGmquZ/XP48c++3uAUDu0Bi+BuuVFbVmDC6bo7sRMdRrWvaHiza3Tlzs85899PTla/LskPRzr9+XJ811Cl5kEuXgxcFdY67mymHyWyQUANG+nMC1O4VZlc95etheBwAxL7fvkxVCgAWxfsWsz3230pRTpDRCVZjk0FjBiUPMNRPzPZdQZhtrJQOuVVmJ7P03Fo6l/9XlG89me4hpe+P0AH9J9+bYZ/x46J5SPweL7xP9YXRmaBsvI9sylLqSvab20sgW92g7ntA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
